### ISSUE TITLE
同问，搞了半天还是不知道怎么填

### ISSUE THREAD

**Issue by mirioer** [SandyCrystal/bilibili_dynamic_gift#2]
那个cookie有很多个，不知道要填哪个，是不是填DedeUserID的数字就行了？我太蠢了连crsf也不知道怎么抓，可以请大佬详细教一下吗？
![微信图片_20210831214130](https://user-images.githubusercontent.com/88777965/131517390-0b0b12c3-e7c4-4af6-8410-0056b2f15f21.png)

**Comment by SandyCrystal** [comment]
cookie先抓下来，然后你找里面的bili_jct，他有的时候会变名字的，以前是crsf。

**Comment by SandyCrystal** [comment]
972556119，不行加我qq问我好了

**Comment by mirioer** [comment]
ok，我再看看，不行就问你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SandyCrystal/bilibili_dynamic_gift"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 晚上11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SandyCrystal/bilibili_dynamic_gift] 同问，搞了半天还是不知道怎么填 (#2)





 
972556119，不行加我qq问我好了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
